dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY} #${...} Gets the data from .env
networks:
  defult: development
  development:
    verify: False
  mainnet-fork-dev:
    verify: False
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
  rinkeby:
    verify: True
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
  ganache-local:
    verify: False
dependencies: 
  #- <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'